### PR TITLE
Others

### PR DESCRIPTION
**Pull request by Furtif**

### CODE REVIEW

**Comment by niicojs** [comment]
I don't like having the full name of a submessage when the message is in the current file.
Also, why changing all those last line?

**Comment by Furtif** [comment]
auto format clang settings

**Comment by niicojs** [comment]
Thanks, last updates look good.
A few things:
- `PlatEightRequest / PlatEightResponse` are already there and named `UnknownPtr8Request/UnknownPtr8Response`
- What is this `PtcToken`? Does not seems to be used.

**Comment by Furtif** [comment]
Ptctoken is [this](https://github.com/Furtif/POGOProtos/blob/master/base/v0.79.2.proto#L4364) but is not used by proto, for plateightrequest response same ... found on lasted shared raw 0.79.2 or other but If have already other name maybe remove this...

**Comment by niicojs** [comment]
If you can remove it, I'll merge.

**Pull request merged**
